[workspace]
resolver = "2"

members = [
    "factordb",
    "factor_engine",
    "factor_macros",
    "factor_tools",
    "factor_tests",

    # Backends
    # Disabled: not functional
    # also needs deadpool-sqlite to upgrade to rusqlite 0.26
    #"factor_sqlite",
]
