[package]
name = "factordb"
version = "0.1.0"
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["memory", "log"]
memory = []
log = ["memory"]

[dependencies]
anyhow = { version = "1.0.45", features = ["backtrace"] }
chrono = { version = "0.4.19", features = ["serde"] }
fnv = "1.0.7"
futures = "0.3.17"
ordered-float = { version = "2.8.0", features = ["serde"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tracing = "0.1.29"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

factor_macros = { version = "0.1", path = "../factor_macros" }
url = { version = "2.2.2", features = ["serde"] }
typescript-type-def = "0.3.1"

[dev-dependencies]
tracing-subscriber = { version = "0.3.1", features = ["fmt"] }
